kind: Service
apiVersion: v1beta1
id: kube-dns
namespace: default
protocol: UDP
port: 53
portalIP: DNS-SERVER-IP
containerPort: 53
labels:
  k8s-app: kube-dns
  kubernetes.io/cluster-service: "true"
selector:
  k8s-app: kube-dns
